### ISSUE TITLE
if extension uploaded is not in array

### ISSUE THREAD

**Issue by retroisbest** [furic/Mini-AJAX-File-Upload-Form#2]
if file extension is not in the accepted file extension array but is bigger then max file size it is shown as being accepted (although this file does not get moved into the uploads folder) - this file upload should show as being invalid.

the same file extension eg *.exe but smaller shows as being an unaccepted file extension

**Comment by sweatyc** [comment]
That's a very old side-project, and I don't think I will look at it soon... it will be great if you can take a look, fork it and fix it...
