### ISSUE TITLE
How to create two forms in same page?

### ISSUE THREAD

**Issue by lucacrippa88** [furic/Mini-AJAX-File-Upload-Form#3]
Hi, I'd like to create two upload forms in the same page, one for images and one for pdf files. I already created another upload.php file and linked it in the new form, and I edited / duplicated CSS. But there is something in the js files that prevent me to create another upload form. By duplicating ids (#upload1, #drop1 etc) it's not working. Where do I have to work in js to have this working?
Thank you

**Comment by sweatyc** [comment]
Make sure duplicate all code in /assets/js/script.js too, but you may need a bit JavaScript knowledge to know what to copy / what to not copy...

Or may be you can try using iframe, to put 2 pages into 1:
https://stackoverflow.com/questions/8068578/how-do-i-use-multiple-iframes-in-my-html-page

Personally I never used iframe so I don't know if that works....

Also this project havn't been updated for 3 years and I'm not gotta support it. I believe there's better solution out there....
